// Copyright (C) 2024 jmh
// SPDX-License-Identifier: GPL-3.0-only

using System.Collections.Generic;

namespace Stratum.Droid.Shared
{
    // GENERATED CLASS, SHOULD NOT BE EDITED DIRECTLY
    public static class IconMap
    {
        public static readonly Dictionary<string, int> Service = new Dictionary<string, int>
        {
            { "1password", Resource.Drawable.auth_1password },
            { "adguard", Resource.Drawable.auth_adguard },
            { "adobe", Resource.Drawable.auth_adobe },
            { "alibabacloud", Resource.Drawable.auth_alibabacloud },
            { "alist", Resource.Drawable.auth_alist },
            { "amazon", Resource.Drawable.auth_amazon },
            { "android", Resource.Drawable.auth_android },
            { "apple", Resource.Drawable.auth_apple },
            { "archlinux", Resource.Drawable.auth_archlinux },
            { "asuswebstorage", Resource.Drawable.auth_asuswebstorage },
            { "aws", Resource.Drawable.auth_aws },
            { "azure", Resource.Drawable.auth_azure },
            { "box", Resource.Drawable.auth_box },
            { "canva", Resource.Drawable.auth_canva },
            { "cloudflare", Resource.Drawable.auth_cloudflare },
            { "debian", Resource.Drawable.auth_debian },
            { "default", Resource.Drawable.auth_default },
            { "dell", Resource.Drawable.auth_dell },
            { "discord", Resource.Drawable.auth_discord },
            { "docker", Resource.Drawable.auth_docker },
            { "dropbox", Resource.Drawable.auth_dropbox },
            { "ebay", Resource.Drawable.auth_ebay },
            { "epicgames", Resource.Drawable.auth_epicgames },
            { "facebook", Resource.Drawable.auth_facebook },
            { "fedora", Resource.Drawable.auth_fedora },
            { "firefox", Resource.Drawable.auth_firefox },
            { "gameguardian", Resource.Drawable.auth_gameguardian },
            { "gitea", Resource.Drawable.auth_gitea },
            { "github", Resource.Drawable.auth_github },
            { "gitlab", Resource.Drawable.auth_gitlab },
            { "gmail", Resource.Drawable.auth_gmail },
            { "google", Resource.Drawable.auth_google },
            { "googlecloud", Resource.Drawable.auth_googlecloud },
            { "googledrive", Resource.Drawable.auth_googledrive },
            { "googlefi", Resource.Drawable.auth_googlefi },
            { "googlefiber", Resource.Drawable.auth_googlefiber },
            { "googlefit", Resource.Drawable.auth_googlefit },
            { "googlepay", Resource.Drawable.auth_googlepay },
            { "googleplay", Resource.Drawable.auth_googleplay },
            { "hp", Resource.Drawable.auth_hp },
            { "huawei", Resource.Drawable.auth_huawei },
            { "instagram", Resource.Drawable.auth_instagram },
            { "jetbrains", Resource.Drawable.auth_jetbrains },
            { "jianguoyun", Resource.Drawable.auth_jianguoyun },
            { "lenovo", Resource.Drawable.auth_lenovo },
            { "mathworks", Resource.Drawable.auth_mathworks },
            { "mega", Resource.Drawable.auth_mega },
            { "microsoft", Resource.Drawable.auth_microsoft },
            { "microsofttodo", Resource.Drawable.auth_microsofttodo },
            { "mongodb", Resource.Drawable.auth_mongodb },
            { "nutstore", Resource.Drawable.auth_nutstore },
            { "nvidia", Resource.Drawable.auth_nvidia },
            { "office", Resource.Drawable.auth_office },
            { "onedrive", Resource.Drawable.auth_onedrive },
            { "openai", Resource.Drawable.auth_openai },
            { "opera", Resource.Drawable.auth_opera },
            { "oracle", Resource.Drawable.auth_oracle },
            { "outlook", Resource.Drawable.auth_outlook },
            { "paypal", Resource.Drawable.auth_paypal },
            { "pixiv", Resource.Drawable.auth_pixiv },
            { "pypi", Resource.Drawable.auth_pypi },
            { "raspberrypi", Resource.Drawable.auth_raspberrypi },
            { "realme", Resource.Drawable.auth_realme },
            { "reddit", Resource.Drawable.auth_reddit },
            { "redhat", Resource.Drawable.auth_redhat },
            { "redis", Resource.Drawable.auth_redis },
            { "rockstargames", Resource.Drawable.auth_rockstargames },
            { "snapchat", Resource.Drawable.auth_snapchat },
            { "sony", Resource.Drawable.auth_sony },
            { "spotify", Resource.Drawable.auth_spotify },
            { "steam", Resource.Drawable.auth_steam },
            { "sync", Resource.Drawable.auth_sync },
            { "tencentcloud", Resource.Drawable.auth_tencentcloud },
            { "termius", Resource.Drawable.auth_termius },
            { "tesla", Resource.Drawable.auth_tesla },
            { "tiktok", Resource.Drawable.auth_tiktok },
            { "twitter", Resource.Drawable.auth_twitter },
            { "unity", Resource.Drawable.auth_unity },
            { "visualstudioonline", Resource.Drawable.auth_visualstudioonline },
            { "vmware", Resource.Drawable.auth_vmware },
            { "vrchat", Resource.Drawable.auth_vrchat },
            { "x", Resource.Drawable.auth_x },
            { "xbox", Resource.Drawable.auth_xbox },
            { "xda", Resource.Drawable.auth_xda },
            { "yahoo", Resource.Drawable.auth_yahoo },
            { "yandex", Resource.Drawable.auth_yandex },
            { "youtube", Resource.Drawable.auth_youtube },
        };

        public static readonly Dictionary<string, int> ServiceDark = new Dictionary<string, int>
        {
            { "1password", Resource.Drawable.auth_1password_dark },
            { "amazon", Resource.Drawable.auth_amazon_dark },
            { "aws", Resource.Drawable.auth_aws_dark },
            { "default", Resource.Drawable.auth_default_dark },
            { "epicgames", Resource.Drawable.auth_epicgames_dark },
            { "github", Resource.Drawable.auth_github_dark },
            { "openai", Resource.Drawable.auth_openai_dark },
            { "realme", Resource.Drawable.auth_realme_dark },
            { "sony", Resource.Drawable.auth_sony_dark },
            { "steam", Resource.Drawable.auth_steam_dark },
            { "termius", Resource.Drawable.auth_termius_dark },
            { "tiktok", Resource.Drawable.auth_tiktok_dark },
            { "unity", Resource.Drawable.auth_unity_dark },
            { "x", Resource.Drawable.auth_x_dark },
        };
    }
}